#!/bin/sh
# -----------------------------------------------------------------------------
# doit.sh — build & run the SystemVerilog counter with Verilator
# -----------------------------------------------------------------------------

# cleanup
rm -rf obj_dir
rm -f counter.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace counter.sv --exe counter_tb.cpp

# build C++ project via Makefile automatically generated by Verilator
make -j -C obj_dir/ -f Vcounter.mk Vcounter

# run executable simulation file
obj_dir/Vcounter
