#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f counter.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv counter.sv bin2bcd.sv --exe top_tb.cpp   -CFLAGS "-std=c++17" -CFLAGS "-std=c++17"

#build C++ project via make automatically generated by Verilog 
make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simulation file 
obj_dir/Vtop